server.port: 9001
spring:
  profiles:
    active: local
  application:
    name: commerce-review-service
  data:
    redis:
      host: localhost
      port: 6379

server:
  servlet:
    context-path: /api/review-service


    spring:
      # 테스트 시에는 H2 DB를 사용하도록 명시
      datasource:
        url: jdbc:h2:mem:testdb # mem: 인메모리 모드로 동작
        driver-class-name: org.h2.Driver
        username: sa
        password:

      jpa:
        hibernate:
          ddl-auto: create-drop # 테스트 시작 시 테이블을 생성하고, 끝나면 삭제
        properties:
          hibernate:
          # H2용 SQL 문법을 사용하도록 설정


