server:
  port: 8000

spring:
  profiles:
    group:
      local: default, local
      prod: default, prod
  application:
    name: gateway

---

spring:
  config:
    activate:
      on-profile: local
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: review-service
              uri: lb://commerce-review-service
              predicates:
                - Path=/api/review-service/**
            - id: member-service
              uri: http://localhost:8888
              predicates:
                - Path=/api/member-service/**

---

spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: review-service
              uri: lb://commerce-review-service
              predicates:
                - Path=/api/review-service/**
            - id: member-service
              uri: http://member-service.commerce.local:8080
              predicates:
                - Path=/api/member-service/**