spring:
  application:
    name: commerce-product-core

logging:
  config: classpath:logback-spring.xml
  file:
    # 파일 저장할 경로
    path: /logs
  level:
    root: warn
    org.springframework.boot.autoconfigure: warn
    innercircle.commerce.product.core: debug
