spring:
  application:
    name: commerce-product-core

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true

logging:
  config: classpath:logback-spring.xml
  file:
    # 파일 저장할 경로
    path: /logs
  level:
    root: warn
    org.springframework.boot.autoconfigure: warn
    innercircle.commerce.product.core: debug
