spring:
  application:
    name: commerce-product-core
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

logging:
  config: classpath:logback-spring.xml
  file:
    # 파일 저장할 경로
    path: /logs
  level:
    root: warn
    org.springframework.boot.autoconfigure: warn
    innercircle.commerce.product.core: debug
