version: '3.8'

services:
  elasticsearch:
    build:
      context: ./docker/elasticsearch
      dockerfile: Dockerfile
    container_name: commerce-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./src/main/resources/synonyms.txt:/usr/share/elasticsearch/config/synonyms.txt
    networks:
      - commerce-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: commerce-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - commerce-network

volumes:
  elasticsearch-data:
    driver: local

networks:
  commerce-network:
    driver: bridge