spring:
  profiles:
    active: dev
  config:
    import:
      - classpath:application-core.yml
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    innercircle.commerce.product.admin: debug

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-southeast-2
    s3:
      bucket: innercircle-commerce1
      base-url: s3://innercircle-commerce1

app:
  image:
    max-file-size: 5242880 # 5MB