spring:
  application:
    name: order-api-service
  profiles:
    # prod: 운영, dev: 개발
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: jdbc:postgresql://158.179.172.168:5433/postgres
    username: postgres
    password: commerce1234!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false


logging:
  config: classpath:logback-spring.xml
  file:
    # 파일 저장할 경로
    path: /logs
  level:
    root: INFO
    innercircle.commerce.order: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs

---
spring:
  config:
    activate:
      on-profile: test

logging:
  level:
    root: WARN
    innercircle.commerce.order: INFO

